START TRANSACTION;

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id character varying(100),
    entity_type character varying(100) NOT NULL,
    entity_id bigint NOT NULL,
    action character varying(20) NOT NULL,
    before_values jsonb,
    after_values jsonb,
    occurred_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY (id)
);

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    closing_day integer NOT NULL,
    billing_customer_id bigint,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_customers" PRIMARY KEY (id),
    CONSTRAINT "FK_customers_customers_billing_customer_id" FOREIGN KEY (billing_customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);

CREATE TABLE tax_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT "PK_tax_categories" PRIMARY KEY (id)
);

CREATE TABLE warehouses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_warehouses" PRIMARY KEY (id)
);

CREATE TABLE sales_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    status character varying(20) NOT NULL,
    customer_id bigint NOT NULL,
    number character varying(20) NOT NULL,
    ordered_on date NOT NULL,
    CONSTRAINT "PK_sales_orders" PRIMARY KEY (id),
    CONSTRAINT "FK_sales_orders_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    unit character varying(10) NOT NULL,
    tax_category_id bigint NOT NULL,
    standard_price numeric(15,2) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_products" PRIMARY KEY (id),
    CONSTRAINT "FK_products_tax_categories_tax_category_id" FOREIGN KEY (tax_category_id) REFERENCES tax_categories (id) ON DELETE RESTRICT
);

CREATE TABLE tax_rates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tax_category_id bigint NOT NULL,
    rate numeric(5,2) NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    CONSTRAINT "PK_tax_rates" PRIMARY KEY (id),
    CONSTRAINT ck_tax_rates_valid_period CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT "FK_tax_rates_tax_categories_tax_category_id" FOREIGN KEY (tax_category_id) REFERENCES tax_categories (id) ON DELETE RESTRICT
);

CREATE TABLE shipments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    status character varying(20) NOT NULL,
    shipped_on date,
    number character varying(20) NOT NULL,
    sales_order_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT "PK_shipments" PRIMARY KEY (id),
    CONSTRAINT "FK_shipments_sales_orders_sales_order_id" FOREIGN KEY (sales_order_id) REFERENCES sales_orders (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_shipments_warehouses_warehouse_id" FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT
);

CREATE TABLE sales_order_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    quantity numeric(15,3) NOT NULL,
    unit_price numeric(15,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    shipped_quantity numeric(15,3) NOT NULL,
    returned_quantity numeric(15,3) NOT NULL,
    product_id bigint NOT NULL,
    sales_order_id bigint NOT NULL,
    CONSTRAINT "PK_sales_order_lines" PRIMARY KEY (id),
    CONSTRAINT "FK_sales_order_lines_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_sales_order_lines_sales_orders_sales_order_id" FOREIGN KEY (sales_order_id) REFERENCES sales_orders (id) ON DELETE RESTRICT
);

CREATE TABLE sales_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    recorded_on date NOT NULL,
    shipment_id bigint,
    billing_customer_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    number character varying(20) NOT NULL,
    CONSTRAINT "PK_sales_records" PRIMARY KEY (id),
    CONSTRAINT "FK_sales_records_customers_billing_customer_id" FOREIGN KEY (billing_customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_sales_records_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_sales_records_shipments_shipment_id" FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE RESTRICT
);

CREATE TABLE shipment_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sales_order_line_id bigint NOT NULL,
    quantity numeric(15,3) NOT NULL,
    shipment_id bigint NOT NULL,
    CONSTRAINT "PK_shipment_lines" PRIMARY KEY (id),
    CONSTRAINT "FK_shipment_lines_sales_order_lines_sales_order_line_id" FOREIGN KEY (sales_order_line_id) REFERENCES sales_order_lines (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_shipment_lines_shipments_shipment_id" FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE RESTRICT
);

CREATE TABLE sales_record_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sales_order_line_id bigint NOT NULL,
    quantity numeric(15,3) NOT NULL,
    unit_price numeric(15,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    amount numeric(15,0) NOT NULL,
    sales_record_id bigint NOT NULL,
    CONSTRAINT "PK_sales_record_lines" PRIMARY KEY (id),
    CONSTRAINT "FK_sales_record_lines_sales_order_lines_sales_order_line_id" FOREIGN KEY (sales_order_line_id) REFERENCES sales_order_lines (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_sales_record_lines_sales_records_sales_record_id" FOREIGN KEY (sales_record_id) REFERENCES sales_records (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_audit_logs_entity_type_entity_id" ON audit_logs (entity_type, entity_id);

CREATE INDEX "IX_customers_billing_customer_id" ON customers (billing_customer_id);

CREATE UNIQUE INDEX "IX_customers_code" ON customers (code);

CREATE UNIQUE INDEX "IX_products_code" ON products (code);

CREATE INDEX "IX_products_tax_category_id" ON products (tax_category_id);

CREATE INDEX "IX_sales_order_lines_product_id" ON sales_order_lines (product_id);

CREATE INDEX "IX_sales_order_lines_sales_order_id" ON sales_order_lines (sales_order_id);

CREATE INDEX "IX_sales_orders_customer_id" ON sales_orders (customer_id);

CREATE UNIQUE INDEX "IX_sales_orders_number" ON sales_orders (number);

CREATE INDEX "IX_sales_record_lines_sales_order_line_id" ON sales_record_lines (sales_order_line_id);

CREATE INDEX "IX_sales_record_lines_sales_record_id" ON sales_record_lines (sales_record_id);

CREATE INDEX "IX_sales_records_billing_customer_id" ON sales_records (billing_customer_id);

CREATE INDEX "IX_sales_records_customer_id" ON sales_records (customer_id);

CREATE UNIQUE INDEX "IX_sales_records_number" ON sales_records (number);

CREATE INDEX "IX_sales_records_shipment_id" ON sales_records (shipment_id);

CREATE INDEX "IX_shipment_lines_sales_order_line_id" ON shipment_lines (sales_order_line_id);

CREATE UNIQUE INDEX "IX_shipment_lines_shipment_id_sales_order_line_id" ON shipment_lines (shipment_id, sales_order_line_id);

CREATE UNIQUE INDEX "IX_shipments_number" ON shipments (number);

CREATE INDEX "IX_shipments_sales_order_id" ON shipments (sales_order_id);

CREATE INDEX "IX_shipments_warehouse_id" ON shipments (warehouse_id);

CREATE UNIQUE INDEX "IX_tax_categories_code" ON tax_categories (code);

CREATE UNIQUE INDEX "IX_tax_rates_tax_category_id_valid_from" ON tax_rates (tax_category_id, valid_from);

CREATE UNIQUE INDEX "IX_warehouses_code" ON warehouses (code);

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE tax_rates ADD CONSTRAINT ex_tax_rates_no_overlap EXCLUDE USING gist (tax_category_id WITH =, daterange(valid_from, valid_to, '[]') WITH &&);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261007003355_AddStageOneTables', '8.0.31');

COMMIT;

